#!/bin/sh

c_echo() {
    printf "hnhx \033[36m::\033[0m $*\n"
}

if [ $(id -u) -ne 0 ]; then
    c_echo You need to run hnhx as root!
    exit
fi

if [ -z "${1}" -o -z "${2}" ]; then
    c_echo Usage: hnhx \[process name\] \[.so file\]
    exit
fi

pid=$(pidof ${1})
if [ -z ${pid} ]; then
    c_echo Invalid process \(${1}\)!
    exit
fi

c_echo ${1} \(${pid}\) is a valid process

so=$(realpath ${2})
if [ ! -f $so ]; then
    c_echo Invalid .so file \(${2}\)!
    exit
fi

c_echo ${so} exists

gdb -n -p ${pid} -batch-silent \
    -ex "set \$__libc_dlopen_mode=(void*(*)(const char*, int))__libc_dlopen_mode" \
    -ex "call \$__libc_dlopen_mode(\"${so}\", 2)" \
    -ex "quit" 2>/dev/null

c_echo Injected ${2} into ${1} \(${pid}\)
